// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeTrade.Backend.Data;

#nullable disable

namespace VibeTrade.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424080657_TrustScoreLedger")]
    partial class TrustScoreLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.AuthPendingOtpRow", b =>
                {
                    b.Property<string>("PhoneDigits")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CodeLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PhoneDigits");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("auth_pending_otps", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.AuthSessionRow", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Token");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatMessageRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("ThreadId", "CreatedAtUtc");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatNotificationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuthorStoreName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("AuthorTrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MessagePreview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetaJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OfferId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RecipientUserId", "CreatedAtUtc");

                    b.ToTable("chat_notifications", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatRouteSheetRow", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouteSheetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PayloadJson");

                    b.Property<bool>("PublishedToPlatform")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ThreadId", "RouteSheetId");

                    b.HasIndex("ThreadId");

                    b.ToTable("chat_route_sheets", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatThreadRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BuyerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstMessageSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("PurchaseMode")
                        .HasColumnType("boolean");

                    b.Property<string>("SellerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("OfferId");

                    b.HasIndex("SellerUserId");

                    b.HasIndex("OfferId", "BuyerUserId")
                        .IsUnique()
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.ToTable("chat_threads", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.EmergentOfferRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OfferQa")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("OfferQaJson");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublisherUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RetractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RouteSheetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouteSheetSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("SnapshotJson");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("ThreadId", "RouteSheetId")
                        .IsUnique();

                    b.HasIndex("Kind", "RetractedAtUtc", "PublishedAtUtc");

                    b.ToTable("emergent_offers", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.MarketWorkspaceRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("market_workspaces", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.OfferLikeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LikerKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LikerKey");

                    b.HasIndex("OfferId");

                    b.HasIndex("OfferId", "LikerKey")
                        .IsUnique();

                    b.ToTable("offer_likes", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.OfferQaCommentLikeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LikerKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QaCommentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LikerKey");

                    b.HasIndex("OfferId", "QaCommentId");

                    b.HasIndex("OfferId", "QaCommentId", "LikerKey")
                        .IsUnique();

                    b.ToTable("offer_qa_comment_likes", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.RouteTramoSubscriptionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("CarrierPhoneSnapshot")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CarrierUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RouteSheetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StopOrden")
                        .HasColumnType("integer");

                    b.Property<string>("StoreServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransportServiceLabel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("ThreadId", "RouteSheetId", "StopId", "CarrierUserId");

                    b.ToTable("route_tramo_subscriptions", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreProductRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentIncluded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainBenefit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("MonedaPrecio")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MonedasJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferQa")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("OfferQaJson");

                    b.Property<string>("PhotoUrlsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("PopularityWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaxesShippingInstall")
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarrantyReturn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("store_products", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CategoriesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JoinedAtMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Pitch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TransportIncluded")
                        .HasColumnType("boolean");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreServiceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependenciasJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entregables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GarantiasJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Incluye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonedasJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("NoIncluye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferQa")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("OfferQaJson");

                    b.Property<string>("PhotoUrlsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("PopularityWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("PropIntelectual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Published")
                        .HasColumnType("boolean");

                    b.Property<string>("RiesgosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("store_services", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoredMediaRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("stored_media", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementMerchandiseLineRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Cantidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Descuento")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DevolucionPlazos")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DevolucionQuienPaga")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DevolucionesDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Impuestos")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LinkedStoreProductId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Regulaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TipoEmbalaje")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TradeAgreementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ValorUnitario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TradeAgreementId");

                    b.ToTable("trade_agreement_merchandise_lines", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementMerchandiseMetaRow", b =>
                {
                    b.Property<string>("TradeAgreementId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DevolucionPlazos")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DevolucionQuienPaga")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DevolucionesDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Regulaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoEmbalaje")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TradeAgreementId");

                    b.ToTable("trade_agreement_merchandise_metas", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IncludeMerchandise")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeService")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedByStoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IssuerLabel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespondedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouteSheetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouteSheetUrl")
                        .HasColumnType("text");

                    b.Property<bool>("SellerEditBlockedUntilBuyerResponse")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("ThreadId");

                    b.HasIndex("ThreadId", "Status");

                    b.ToTable("trade_agreements", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceDependenciaRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceItemId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("trade_agreement_service_dependencias", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Configured")
                        .HasColumnType("boolean");

                    b.Property<bool>("DependenciasEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entregables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GarantiasEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GarantiasTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incluye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedStoreServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MedicionCumplimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NivelResponsabilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoIncluye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PenalAtrasoEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PenalAtrasoTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PenalIncumplimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropIntelectual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RiesgosEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ScheduleCalendarYear")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleDefaultWindowEnd")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ScheduleDefaultWindowStart")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TerminacionAvisoDias")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("TerminacionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TiempoEndDate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TiempoStartDate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TradeAgreementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TradeAgreementId");

                    b.ToTable("trade_agreement_service_items", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceMonedaRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ServiceItemId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("trade_agreement_service_monedas", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServicePaymentEntryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceItemId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("trade_agreement_service_payment_entries", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServicePaymentMonthRow", b =>
                {
                    b.Property<string>("ServiceItemId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.HasKey("ServiceItemId", "Month");

                    b.ToTable("trade_agreement_service_payment_months", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceRiesgoRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceItemId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("trade_agreement_service_riesgos", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleDayRow", b =>
                {
                    b.Property<string>("ServiceItemId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("CalendarDay")
                        .HasColumnType("integer");

                    b.HasKey("ServiceItemId", "Month", "CalendarDay");

                    b.ToTable("trade_agreement_service_schedule_days", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleMonthRow", b =>
                {
                    b.Property<string>("ServiceItemId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.HasKey("ServiceItemId", "Month");

                    b.ToTable("trade_agreement_service_schedule_months", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleOverrideRow", b =>
                {
                    b.Property<string>("ServiceItemId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("CalendarDay")
                        .HasColumnType("integer");

                    b.Property<string>("WindowEnd")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("WindowStart")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ServiceItemId", "Month", "CalendarDay");

                    b.ToTable("trade_agreement_service_schedule_overrides", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceTerminacionCausaRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceItemId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("trade_agreement_service_terminacion_causas", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TrustScoreLedgerRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "CreatedAtUtc");

                    b.ToTable("trust_score_ledger", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneDigits")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhoneDisplay")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SavedOfferIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Telegram")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("XAccount")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneDigits")
                        .IsUnique()
                        .HasFilter("\"PhoneDigits\" IS NOT NULL");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.UserContactRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ContactUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OwnerUserId", "ContactUserId")
                        .IsUnique()
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.ToTable("user_contacts", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.UserOfferInteractionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OfferId");

                    b.HasIndex("UserId");

                    b.HasIndex("OfferId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("user_offer_interactions", (string)null);
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatMessageRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.ChatThreadRow", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatRouteSheetRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.ChatThreadRow", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.RouteTramoSubscriptionRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.ChatThreadRow", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreProductRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.StoreRow", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.UserAccount", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreServiceRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.StoreRow", "Store")
                        .WithMany("Services")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementMerchandiseLineRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementRow", "TradeAgreement")
                        .WithMany("MerchandiseLines")
                        .HasForeignKey("TradeAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeAgreement");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementMerchandiseMetaRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementRow", "TradeAgreement")
                        .WithOne("MerchandiseMeta")
                        .HasForeignKey("VibeTrade.Backend.Data.Entities.TradeAgreementMerchandiseMetaRow", "TradeAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeAgreement");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.ChatThreadRow", "Thread")
                        .WithMany("TradeAgreements")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceDependenciaRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("DependenciaItems")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementRow", "TradeAgreement")
                        .WithMany("ServiceItems")
                        .HasForeignKey("TradeAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeAgreement");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceMonedaRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("MonedasAceptadas")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServicePaymentEntryRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("PaymentEntries")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServicePaymentMonthRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("PaymentMonths")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceRiesgoRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("RiesgoItems")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleDayRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleMonthRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("ScheduleMonths")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceScheduleOverrideRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("ScheduleOverrides")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceTerminacionCausaRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", "ServiceItem")
                        .WithMany("TerminacionCausas")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.UserContactRow", b =>
                {
                    b.HasOne("VibeTrade.Backend.Data.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ContactUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeTrade.Backend.Data.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.ChatThreadRow", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("TradeAgreements");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.StoreRow", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementRow", b =>
                {
                    b.Navigation("MerchandiseLines");

                    b.Navigation("MerchandiseMeta");

                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.TradeAgreementServiceItemRow", b =>
                {
                    b.Navigation("DependenciaItems");

                    b.Navigation("MonedasAceptadas");

                    b.Navigation("PaymentEntries");

                    b.Navigation("PaymentMonths");

                    b.Navigation("RiesgoItems");

                    b.Navigation("ScheduleDays");

                    b.Navigation("ScheduleMonths");

                    b.Navigation("ScheduleOverrides");

                    b.Navigation("TerminacionCausas");
                });

            modelBuilder.Entity("VibeTrade.Backend.Data.Entities.UserAccount", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
